// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjfcbfszrkvblzxkcmyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qZmNiZnN6cmt2Ymx6eGtjbXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzM1NTYsImV4cCI6MjA2OTY0OTU1Nn0.gNTBUmRTk_JPBMb-zuILNih2i-msP0JtArjERg6NQH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});